baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "harbor"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.GEOJSON]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "index"
    notAlternative = true

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"
