name: github pages

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0
      - name: Install Node dependencies
        run: |
          yarn install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
          extended: true
      - name: Build Hugo site
        run: hugo
